/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @returns {number}
 */
exports.q2 = function () {
    let total = 0;
    let last_num = 1;
    let current_num = 2;
    while (current_num <= 4000000) {
        if (isEven(current_num)) {
            total += current_num;
        }
        let tmp_current_num = current_num;
        current_num += last_num;
        last_num = tmp_current_num;
    }
    return total;
};

/**
 * Is number a an even number.
 *
 * @return {boolean}
 */
function isEven(a) {
    return a % 2 === 0;
}
